### ISSUE TITLE
Integration doesn't show up on list

### ISSUE THREAD

**Issue by daveblank** [codingcyclist/ha_strava#21]
Running HA version 2020.12.2 and HACS version 1.9.0.

Added the repository for ha_strava, and the directory shows up in custom_components.

For some reason I don't get an option to add the integration in configuration.  No errors at all in the log (enabled debug logging on custom_components).

I'm sure I'm doing something wrong here, but I could use ideas on how to troubleshoot.

![image](https://user-images.githubusercontent.com/76796062/103388429-d8b5ce80-4abd-11eb-8dbb-d13a680016c9.png)

![image](https://user-images.githubusercontent.com/76796062/103388452-ec613500-4abd-11eb-9cbc-da0de4e65cb2.png)

**Comment by codingcyclist** [comment]
Hi @daveblank 
this might be a latency issue with HACS. Other users reported similar troubles (see here in the [HomeAssistant community forum](https://community.home-assistant.io/t/strava-home-assistant-integration/213867/17)).

What happens if you add the Repository to HACS, wait a little while and then try again whether you can find the integration in your HA integrations search bar?

**Comment by daveblank** [comment]
Thanks for the response.  It's been a week now and it's still not in the list of available integrations (and I've got a few other integrations from HACS that work in the same way that are appearing).

I'm not sure this is an issue with the ha_strava integration or just something weird with homeassistant, I can definitely make a post in the HA forums and see if anyone has ideas.

**Comment by codingcyclist** [comment]
Hugh, that is indeed an unexpected behavior. I think reaching out to the HA community is always a good idea. On other thing which you could try in addition is to remove the repository from HACS, restart your HomeAssistant instance, and add the repository back to HACS after the restart (an the may restart again, just to be sure).

In any way, please keep me posted so that we can resolve this issue together.

**Comment by daveblank** [comment]
Will give it a try later today and keep you posted.  Thanks for making the integration, plan to setup a gauge to track percentage of the 1,000 miles I want to run this year (and how far ahead/behind I am).

**Comment by daveblank** [comment]
Wow, that's super weird.  Removed and readded the repository and it showed up under integrations immediately (I did this before opening the issue).  Added clientid/secret and sensors are there and working.  Computers are weird, will close this one out.

**Comment by Fleshi1981** [comment]
> Wow, that's super weird. Removed and readded the repository and it showed up under integrations immediately (I did this before opening the issue). Added clientid/secret and sensors are there and working. Computers are weird, will close this one out.

I have exact the same issue. I also did the same "steps" you did, only unfortunately for me the Strava integration doesn't show up.
